### ISSUE TITLE
Error using require('react-bootstrap-datetimepicker').DateTimePickerDays;

### ISSUE THREAD

**Issue by babyboypk** [quri/react-bootstrap-datetimepicker#10]
I Using require('react-bootstrap-datetimepicker').DateTimePickerDays;. Console log of firefox show error "TypeError: type is undefined  (type.defaultProps) { ". How can I use DateTimePickerDays.........
Thank You.

**Comment by chollier** [comment]
See the docs or example, you need to use `<DateTimeField>` -> http://dev.quri.com/react-bootstrap-datetimepicker/
