### ISSUE TITLE
Add CSS to the repo

### ISSUE THREAD

**Issue by binarykitchen** [quri/react-bootstrap-datetimepicker#11]
I think it would be good to add the CSS file to the repository. Because I guess, everyone who is going to use this package also needs the styles. Pretty obvious I guess ;)

**Comment by razagill** [comment]
+1 for having CSS in the repo.

**Comment by chollier** [comment]
Indeed, I use to do it but stopped. I'm adding it back in dist/css

**Comment by chollier** [comment]
I just published v0.0.10 to npm
