### ISSUE TITLE
The Component use an outdated version of React Bootstrap

### ISSUE THREAD

**Issue by chollier** [quri/react-bootstrap-datetimepicker#111]

**Comment by ziflex** [comment]
Hi!
Thanks for a good component.
But I've got an issue with its dependencies and with react-bootstrap itself.

Is it possible to remove it from dependencies  and leave one in devDependneices for dev and test purposes ?
The thing is that I use react-bootstrap with browserify, and browserify add in bundle my version of react-bootstrap and version of you component.

**Comment by dacostafilipe** [comment]
+1

**Comment by chollier** [comment]
we removed the dependency to react-bootstrap
