### ISSUE TITLE
Unable to follow examples

### ISSUE THREAD

**Issue by seekshiva** [quri/react-bootstrap-datetimepicker#116]
I get this error when trying to render `<DateTimePicker />`:

Uncaught Error: Invariant Violation: DateTimeField.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object

**Comment by dibyas** [comment]
can you send your code? what is trying to return. R u returning any non react component.

**Comment by seekshiva** [comment]
@dibyas 

My render method only has this:

```
    render() {
        return <DateTimeField/>
    }
```

**Comment by seekshiva** [comment]
I tried changing it to return `<div>hi</div>` and it works without an error. Changing it back to `<DateTimeField />` brings back the error.`

**Comment by alfonsoperez** [comment]
@seekshiva have you imported the component?
    
    import DateTimeField from "react-bootstrap-datetimepicker";

**Comment by alfonsoperez** [comment]
@seekshiva have you imported the component?

Example, depending on your project:
  
    import DateTimeField from "react-bootstrap-datetimepicker";
or

    var DateTimeField = require('react-bootstrap-datetimepicker');

If yes, try doing:

    render() {
      console.log(DateTimeField);
      return <div>hi</div>;
    }

And tell me what does it output

**Comment by seekshiva** [comment]
Seems like the issue was caused because my project was using an older version of react instead of the one that datetime-picker required. So, two different versions of react were being used, and that caused the issue.

Fixed it now.
