### ISSUE TITLE
Upgrade to React 0.14

### ISSUE THREAD

**Issue by implicitdef** [quri/react-bootstrap-datetimepicker#117]
I'm using this plugin with React 0.14.0. So far it seems to work but I get some warnings, nothing dramatic. Would you considerer fixing them and targeting React 0.14 for a next version ?

when opening the datetime picker :
```
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `DateTimeField`.
```

when clicking on a random day in the calendar :
```
Warning: `div` was passed a style object that has previously been mutated. Mutating `style` is deprecated. Consider cloning it beforehand. Check the `render` of `DateTimePicker`. Previous style: {display: "block", position: "absolute", top: 40, left: "auto", right: 40}. Mutated style: {display: "none", position: "absolute", top: 40, left: -9999, right: 40}.
```

**Comment by iyoukeyyewei** [comment]
has the same issue

**Comment by zinevych** [comment]
me too

**Comment by chollier** [comment]
I definitely consider making it React 0.14 compliant, pull requests would be greatly appreciated though :)

**Comment by snowcxt** [comment]
same issue too

**Comment by barbalex** [comment]
+1 same issue

**Comment by snowcxt** [comment]
any update?

**Comment by dkulichkin** [comment]
Could you please update npm package with this upgrades as well?

**Comment by andrewhl** [comment]
Yes, please do this.

**Comment by chollier** [comment]
I just published [v0.0.22](https://github.com/quri/react-bootstrap-datetimepicker/releases/tag/v0.0.22)

**Comment by chollier** [comment]
Thanks @alfonsoperez !

**Comment by barbalex** [comment]
nice!
