### ISSUE TITLE
Add webpack-dev-server to dpendencies

### ISSUE THREAD

**Issue by The-Q** [quri/react-bootstrap-datetimepicker#12]
I'm a complete node beginner, and I wanted to see examples your lib. So I done as said in examples, but when I tried to execute ```npm run examples``` I got error saying that webpack-dev-server is not found. After about a hour of googling/meditating etc. I found that in ```package.json``` file there is only dependency for webpack only. Maybe there should be webpack-dev-server dependency as well? Or task for running examples is incorrect?

**Comment by chollier** [comment]
you're right, thanks for noticing me, I'll take care of it soon
