### ISSUE TITLE
Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `DateTimeField`.

### ISSUE THREAD

**Issue by wang3g** [quri/react-bootstrap-datetimepicker#121]
I am trying to use react-bootstrap-datetimepicker in my project. But I got weird result. What I did is:
1) npm install react-bootstrap-datetimepicker --save
2) add "require('react-bootstrap-datetimepicker/css/bootstrap-datetimepicker.css');" in my code
3) add "
     \<div className="col-xs-6"\>
           \<DateTimeField />
      \</div>"
   in the render function.

After building the code, DatePicker is displayed on the page. But when I click the icon, some warning messages are shown. Also part of the popup calendar window is out of the page.
![screen shot 2015-11-02 at 11 23 05 am](https://cloud.githubusercontent.com/assets/6946817/10872358/3270a5e6-8154-11e5-84b1-8586b6facb8b.png)

Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `DateTimeField`.warning @ warning.js:45legacyGetDOMNode @ ReactDOMComponent.js:88DateTimeField.onClick @ DateTimeField.js:274ReactErrorUtils.invokeGuardedCallback 
DateTimeField.js:411 1446769200000
warning.js:45 Warning: `div` was passed a style object that has previously been mutated. Mutating `style` is deprecated. Consider cloning it beforehand. Check the `render` of `DateTimePicker`. Previous style: {display: "block", position: "absolute", top: 40, left: "auto", right: 40}. Mutated style: {display: "none", position: "absolute", top: 40, left: -9999, right: 40}.

What did I miss? Please help. Thanks a lot.

**Comment by praneybehl** [comment]
+1 I confirm this, seems to be from the new React update.

**Comment by chollier** [comment]
Just published 0.0.22
