### ISSUE TITLE
Can the dateTime prop be really any string?

### ISSUE THREAD

**Issue by binarykitchen** [quri/react-bootstrap-datetimepicker#13]
I tried to pass on a string like `Wed Jan 21 2015 16:38:18 GMT+1300 (NZDT)`, defined the inputFormat as `YY/MM/DD` but somehow it shows that date wrong, as `70/01/01`. Any ideas why?

**Comment by chollier** [comment]
If using that format, you'll want to pass a format prop defining said format. It has to use momentjs formatting : http://momentjs.com/docs/#/parsing/string-format/

**Comment by binarykitchen** [comment]
Got it!
