### ISSUE TITLE
showToday not working

### ISSUE THREAD

**Issue by razagill** [quri/react-bootstrap-datetimepicker#14]
showToday prop seems to be not working. Tried setting it to 'true', but it still shows current from January 1970.

**Comment by chollier** [comment]
The `showToday` prop is just to have an indicator of today's date on the days view :

with true :
![screenshot 2015-02-21 19 15 33](https://cloud.githubusercontent.com/assets/1869/6317261/346e777e-b9fe-11e4-9bf6-11cd2ff346d8.png)

vs with false :
![screenshot 2015-02-21 19 15 42](https://cloud.githubusercontent.com/assets/1869/6317263/3c72f990-b9fe-11e4-9a10-36a2b550f101.png)

**Comment by razagill** [comment]
Oh okay, got it thanks.
