### ISSUE TITLE
Get value via refs?

### ISSUE THREAD

**Issue by razagill** [quri/react-bootstrap-datetimepicker#15]
Hi thanks for the component again,man.
Just wanted to ask if there is a way to get the current date time value via refs? Or must we have to implement an onChange listener?

**Comment by chollier** [comment]
Hi @razagill,

I would really advise no to use refs to get some values. And in general, this goes a little bit against one of the core React principles that is to avoid 2-way data binding. refs should only be used in very specific cases (http://facebook.github.io/react/docs/more-about-refs.html#cautions). I'll simply quote React's doc : 
> If you have not programmed several apps with React, your first inclination is usually going to be to try to use refs to "make things happen" in your app. If this is the case, take a moment and think more critically about where state should be owned in the component hierarchy. Often, it becomes clear that the proper place to "own" that state is at a higher level in the hierarchy. Placing the state there often eliminates any desire to use refs to "make things happen" – instead, the data flow will usually accomplish your goal.

**Comment by razagill** [comment]
Got it. I think it just seemed so easy to just get the value from refs like we do from text controls etc, that I thought I'm actually missing something. Thanks for the clarification.
