### ISSUE TITLE
Remove glyph in input field and start the picker onFocus

### ISSUE THREAD

**Issue by martinbkure** [quri/react-bootstrap-datetimepicker#154]
Hi, 
is there a way to remove the calendar-glyph, so it's just an input field without icon. And then let the input field (onFocus) trigger the datetimepicker?

In the original bootstrap-datetimepicker, it's seems to be a standard feature, but not sure, if it's been implemented in this repo: http://eonasdan.github.io/bootstrap-datetimepicker/

I've looked at this issue, but it doesn't seem to do the trick, though: https://github.com/quri/react-bootstrap-datetimepicker/issues/102

**Comment by kylelamse** [comment]
It seems like it should be obvious behavior that when you click on the input field, the calendar pops up.

**Comment by martinbkure** [comment]
Apparently the code is made default with the glyph. I was hoping for some sort of bool prop, which could set or unset the glyph. But haven't found one yet.

**Comment by martinbkure** [comment]
This is solved in issue #102
