### ISSUE TITLE
DateTimeField does not work as a componentClass (react-bootstrap 0.29.0)

### ISSUE THREAD

**Issue by tanepiper** [quri/react-bootstrap-datetimepicker#165]
With the latest version of react-bootstrap, components are now initialised as a `componentClass` of the new `FormControl` component (see https://react-bootstrap.github.io/components.html#forms).  For example this datepicker would be:

    <FormGroup controlId="formDate" validationState={myDate.error}>
        <ControlLabel>Date</ControlLabel>
        <FormControl componentClass={DateTimeField} mode={'date'} format={'DD/MM/YYYY'} inputFormat={'DD/MM/YYYY'} placeholder="Please select a date" {...myDate} />
        <FormControl.Feedback />
        <HelpBlock>This would be a date picker</HelpBlock>
      </FormGroup>

Currently it does not work.

**Comment by chollier** [comment]
react-bootstrap is not a dependency of this project, while they can work together, they are not interdependent. 
What you can do is make you own wrapper around react-bootstrap-datetimepicker that would use the react-bootstrap API and render a DateTimePicker, I don't see anywhere that `componentClass` can take a ReactComponent though, it seems to be only string

**Comment by tanepiper** [comment]
@chollier If you look at https://github.com/react-bootstrap/react-bootstrap/blob/ae48d58afc2bcfcc36cabec136bba33929387513/src/FormControl.js for example acts like a higher order component where componentClass takes any react component, or a valid element string (since React will just render them, it's just JSX)

However I get your point they aren't interdependent so I'll try see if I can figure it out why it's just not returning the DateTimeField inside the wrapper (which provides validation state, etc)
