### ISSUE TITLE
placement of picker way off when using grid css

### ISSUE THREAD

**Issue by barbalex** [quri/react-bootstrap-datetimepicker#166]
I am using electron.

Because the environment is controlled, I can use the grid css (https://css-tricks.com/snippets/css/complete-guide-grid) by setting the experimental flag in chrome.

This is great for building complex forms.

Unfortunately the picker opens way off of the actual position of the date input :-(

**Comment by joshvanderberg** [comment]
It's anchoring to the nearest fixed position component.  Wrap the date control in a div with a position css element:

		<div style={{position: 'relative'}}>...control</div>

**Comment by barbalex** [comment]
thanks, works nicely!
