### ISSUE TITLE
This repo should be deprecated, there is a better fork.

### ISSUE THREAD

**Issue by andrewmclagan** [quri/react-bootstrap-datetimepicker#187]
No offence intended although having used both of these components in production I can say this fork:

https://github.com/YouCanBookMe/react-datetime

Offers many advantages:

1. Under active development
2. More consistent API
3. More performant

I would ask the developer to consider placing a deprecated notice on this repo so the community is less fragmented. 

Basically "lets work together".

**Comment by chollier** [comment]
will do you're right

**Comment by missmellyg85** [comment]
Please consider placing a deprecated notice so other people don't have to dig for the better fork. 

I would not have known had I not been digging through issues trying to find a solution for a problem I was having.

**Comment by chollier** [comment]
just did so
