### ISSUE TITLE
Hard to use keyboard for direct input

### ISSUE THREAD

**Issue by torarvid** [quri/react-bootstrap-datetimepicker#23]
When providing both a `datetime` and an `onChange` as props, it is just about impossible to use the keyboard to change the value.

Say for instance that the field has a value `1979-11-18 9:17:25 AM`, and you just want to change the month from 11 to 3. I would place the cursor behind 11, press backspace, and then immediately it would validate, re-bind the validated value, and the cursor jumps to the end...

I see that internally you set `value={..}` on the input field.. Have you thought about using `defaultValue` instead?

**Comment by chollier** [comment]
Hey !

I just fixed that with 0.0.13
