### ISSUE TITLE
No release done since 0.0.8

### ISSUE THREAD

**Issue by olethanh** [quri/react-bootstrap-datetimepicker#29]
Hello,

no Github release was done since 0.0.8.

**Comment by chollier** [comment]
I just release 0.0.13 :)

**Comment by olethanh** [comment]
thanks :)

note: it's still missing the css inside the dist directory ^^

**Comment by chollier** [comment]
but it's in the /css directory isn't that ok ?

**Comment by olethanh** [comment]
honestly I don't know much about JS packaging so I'm not sure but I think the dist is supposed to represent the freezed release (all the files needed to make the project works) so IMHO the css should be included

**Comment by chollier** [comment]
Hrmm I won't pretend to be a JS packaging master, but as a matter of fact, most people are using npm packages now (from what I've seen the past few months). And the css directory is indeed included in the css package (just try `npm install react-bootstrap-datetimepicker --save`, you'll see `/css` is included in `node_modules/react-bootstrap-datetimepicker/css`)
