### ISSUE TITLE
TypeError: __webpack_require__(...) is undefined

### ISSUE THREAD

**Issue by bazo** [quri/react-bootstrap-datetimepicker#37]
hi,

i'm using datepicker as browser global but i get this error in firefox

    TypeError: __webpack_require__(...) is undefined
      Glyphicon = __webpack_require__(4).Glyphicon;

freshly installed from bower, using the unminified version

**Comment by bryanhatwood** [comment]
Ran into this too, had to install and include 'react.backbone'

**Comment by volkanunsal** [comment]
Same here..

**Comment by volkanunsal** [comment]
Figured it out. The Glyphicon variable is not defined. This is why hoisting the variable declarations to the top of the file is a bad idea. You forget which variables are declared and which ones are not. Aside from Glyphicon, Constants also suffer from this issue:

```
var Glyphicon = require('react-bootstrap').Glyphicon;
var Constants = require('./Constants');
```

**Comment by chollier** [comment]
oh my bad.. Thanks @volkanunsal
