### ISSUE TITLE
Hide time switcher

### ISSUE THREAD

**Issue by randrianov** [quri/react-bootstrap-datetimepicker#40]
In original http://eonasdan.github.io/bootstrap-datetimepicker/#min-view-mode
we can manage showing or hiding time switcher when set 'format' option.
In DateTimePicker.js you always render 'picker-switch' btn, so please, keep it sync with original.
Many thanks!

**Comment by chollier** [comment]
This have partly been solved with 0.0.16, see the [demo page](http://dev.quri.com/react-bootstrap-datetimepicker/).
