### ISSUE TITLE
Where can I find examples of how to use this component?

### ISSUE THREAD

**Issue by moroshko** [quri/react-bootstrap-datetimepicker#5]
I tried to include:

    var DateTimePicker = require('react-bootstrap-datetimepicker/DateTimePicker');

and then render:

    <DateTimePicker />

But, I get:
> Uncaught TypeError: Cannot read property 'classSet' of undefined

**Comment by chollier** [comment]
Hi @moroshko, I believe your issue with classSet was fixed by the 0.0.7 release.

I also have added a basic example as well as some documention on the [README](../README.md).
