### ISSUE TITLE
Selecting previous (or next) month's day from current month's view does not select correct date

### ISSUE THREAD

**Issue by MarkoR** [quri/react-bootstrap-datetimepicker#51]
The issue is better to describe via example:

If you have May opened in the calendar and you would like to choose 30th of April from the calendar directly without moving to April through upper arrows, the selected date is 30th of May and not 30th of April as it should be. The same happens if you choose next month's first days like 1st, 2nd or 3rd. If you choose 1st of June without moving to June as a month, the selected date will be 1st of May instead of 1st of June. Tested with Google Chrome (Win 8.1).

**Comment by rojoca** [comment]
Looks like this is fixed in 0.0.16
