### ISSUE TITLE
require("react/addons") is deprecated

### ISSUE THREAD

**Issue by danielsoner** [quri/react-bootstrap-datetimepicker#61]
Hi, 
I have been using React 0.14.0-alpha3 and I see this warning:
require("react/addons") is deprecated. Access using require("react/addons/{addon}") instead.

See the image attached.
![warning](https://cloud.githubusercontent.com/assets/12113326/8188660/02fa28f6-140c-11e5-9467-4d66bfa71934.png)

**Comment by chollier** [comment]
Hey @danielsoner, thanks for reporting, I haven't looked at React 0.14 yet. I'll try to do a cleanup soon and address these deprecations / changes.

**Comment by danielsoner** [comment]
That sounds good!

**Comment by chollier** [comment]
I wasn't using react/addons anyway, I just converted the code to ES2015 and removed these references, I'll publish a new version soon.
