### ISSUE TITLE
DateTime field doesn't update on this.setState()

### ISSUE THREAD

**Issue by eduvon0220** [quri/react-bootstrap-datetimepicker#62]
I am having an issue getting the datetime field to update after setting the state using a callback attached to onChange event.  How can I access the value of the datetime field so I can update this value by using setState?

```
<DateTimeField inputFormat="MM/DD/YY h:mm A" onChange={this.handleChange}  value={this.state.start_time} />
```
```
 handleChange: function(event) {
      this.setState({start_time: event});
    },
```

Thanks so much for your help!

**Comment by gustavoschmidt** [comment]
Use dateTime props instead:
```
<DateTimeField inputFormat="MM/DD/YY h:mm A" onChange={this.handleChange}  dateTime={this.state.start_time} />
```

**Comment by chiedojohn** [comment]
Heck yeah, that seems like it fixed it. Thanks @gustavoschmidt
