### ISSUE TITLE
React.addons.classSet is deprecated.

### ISSUE THREAD

**Issue by Andreyco** [quri/react-bootstrap-datetimepicker#65]
```
Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset
```

**Comment by latifs** [comment]
Hey Guys,
Any news about that, it got reverted and that's it??
Any chances that it will make it back in?
Thanks

**Comment by chollier** [comment]
not it got merged, how ever I didn't publish a new release, give me a moment

**Comment by chollier** [comment]
I just release v0.0.18 that address that issue
