### ISSUE TITLE
The component doesn't work on Firefox 39.0

### ISSUE THREAD

**Issue by Tin-Nguyen** [quri/react-bootstrap-datetimepicker#73]
I'm facing 1 critical issue on the component on my app. Using Firefox browser 39.0, we cannot select the date on datepicker.

I tried to check on the demo page of the component and got the same issue.

<img width="1436" alt="screen shot 2015-07-15 at 3 34 18 pm" src="https://cloud.githubusercontent.com/assets/5414916/8694099/a15cc894-2b06-11e5-9d21-71ea046d84da.png">

Please help to clarify and fix it.

Regards,
Tin Nguyen

**Comment by Tin-Nguyen** [comment]
anyone can help me on the issue?

**Comment by conradfr** [comment]
FWIW it works for me on my project.

**Comment by torarvid** [comment]
@Tin-Nguyen This was fixed by #56 so if you get v0.0.18 or newer this should work for you

**Comment by Tin-Nguyen** [comment]
Thank you. I will check soon
