### ISSUE TITLE
Using setState in onChange handler prevents input to update its value

### ISSUE THREAD

**Issue by LoicUV** [quri/react-bootstrap-datetimepicker#86]
```
var myComponent = React.createClass({

    getInitialState() {
        return {
            date: 0
        }
    },

    chooseDate(date) {
        this.setState({date: date});
    },

    render() {
        return (
            <DateTimeField onChange={this.chooseDate}  />
        )
    }

});
```

myComponent state is updated with the new date, but the input doesn't change its text value whenever I use setState in the onChange handler. Any idea why ?

**Comment by busla** [comment]
Had the same problem but I added a moment object to my initial date, like so:

`
  getInitialState: function () { 
    
    return {
        date: moment().format("YYYY-MM-DD HH:mm:ss")
    };
  },
`

**Comment by LoicUV** [comment]
Tried :
```
var myComponent = React.createClass({

    getInitialState() {
        return {
            date: moment().format("YYYY-MM-DD HH:mm:ss")
        }
    },

    chooseDate(date) {
        this.setState({date: date});
    },

    render() {
        return (
            <DateTimeField onChange={this.chooseDate}  />
        )
    }

});
```

Doesn't work either. What bothers me is why calling setState in the event handler prevents the input to update its value... ?

**Comment by busla** [comment]
I have other attributes on <DateTimeField /> so let me post them also. It might give something more to work with.


```
  getInitialState: function () { 
    
    return {
        date: moment().format('YYYY-MM-DDTHH:mm:ss.SSS')
    };
  },

  changeDate: function(date) {    
    this.setState({ date: date });    
  },

  render: function(){
             <DateTimeField              
                inputFormat='D. MMM - h:mm' 
                onChange={this.changeDate} 
                format="YYYY-MM-DDTHH:mm:ss.SSS"
                dateTime={this.state.date}  />
  }
```

**Comment by LoicUV** [comment]
It works now when passing `dateTime={this.state.date}`.
It still doesn't solve the initial issue though.

**Comment by chollier** [comment]
Hi Loïc,

Regarding you very first post, the component has no way to know about the parent's state unless you pass some props down. You need to specify `dateTime` so when handleChange change the state of `myComponent` then it bubbles down to DateTimeField. Your "initial issue" is a misunderstanding of basic react principles. You should look at https://facebook.github.io/react/docs/forms.html#controlled-components, this explains the principle of a Controlled Component which is the behavior of DateTimeField.

**Comment by busla** [comment]
Whats your inputFormat value? Have you tried to change that?

**Comment by chollier** [comment]
I added an example which shows how to use it in the context of a controlled component : http://dev.quri.com/react-bootstrap-datetimepicker/

**Comment by LoicUV** [comment]
Great thanks :)
