### ISSUE TITLE
Controlled component state not updated

### ISSUE THREAD

**Issue by ADumaine** [quri/react-bootstrap-datetimepicker#89]
I am trying to add the datetime picker to a project using https://github.com/jedireza/aqua.  I have been able to add the picker to the new controlled component and it works fine selecting a date and time and updating the field.  But it is not changing the conrcomponent state.

This is the DateTimeControl.jsx:
```javascript
var React = require('react/addons');
var ObjectAssign = require('object-assign');
var ControlGroup = require('../../components/form/ControlGroup');
var ClassNames = require('classnames');
var DateTimeField = require('react-bootstrap-datetimepicker');

var View = React.createClass({
    getDefaultProps: function () {

        return {
            type: 'test',
            autoCapitalize: 'off'
        };
    },
    render: function () {

        var inputClasses = ClassNames(ObjectAssign({
            'form-control': true
        }, this.props.inputClasses));


        return (
            <ControlGroup hasError={this.props.hasError}
                          label={this.props.label}
                          help={this.props.help}>

                <DateTimeField ref="inputField"
                       type={this.props.type}
                       autoCapitalize={this.props.autoCapitalize}
                       className={inputClasses}
                       name={this.props.name}
                       placeholder={this.props.placeholder}
                       value={this.props.value}
                       valueLink={this.props.valueLink}
                       disabled={this.props.disabled ? 'disabled': undefined}
                       inputFormat='MM/DD/YYYY hh:mm A'
                       onChange={this.props.onChange} />
            </ControlGroup>
        );
    }
});
module.exports = View;
```

This is the control in the form:
```javascript
 <DateTimeField name="start_time"
       ref="start_time"
       label="Start Date and Time"
       hasError={this.props.data.hasError.start_time}
       valueLink={this.linkState('start_time')}
       help={this.props.data.help.start_time}
       disabled={this.props.data.loading}/>
```
I'm using the react plugin for chrome to check the state.  The other fields within the component are getting updated.  The start_time field has the initial date in the state from the database but the state of the form component does not get updated from the datepicker (the field component and field value does).

Shows the current field state on an un-submitted form in their updated local state (the start_time state never changes):
``` 
   State
     entry_amt: 0
     entry_fee: "10"
     game_status: "1"
     game_type: 1
     gid: 1
     hydrated: true
     prize1_pct: "100"
     prize2_pct: null
     prize3_pct: null
     rounds: 36
     start_time: "0000-00-00"
     user_need: 2
     win_levels: "1"
```
The values in the field:
```
HTML
<div class="bootstrap-datetimepicker-widget dropdown-menu bottom pull-right" style="display: none; position: relative; left: -9999px; top: -20px; right: 40px;" data-reactid=".0.1.1.0.0.1.c.1.1">....
<input type="text" class="form-control" value="08/28/2015 06:39 PM" data-reactid=".0.1.1.0.0.1.c.1.2.0">

REACT plugin 
<t type="date" autoCapitalize="off", className="form-control" name="start_time" valueLink="..." inputFormat = "MM/DD/YYYY hh:mm A" datetime="144081234631" format="x" showToday="true" viewMode="days" daysofWeekDisabled="..." mode="datetime">
```

The field state looks like it gets updated in React plugin.  It is just the main parent controlled component that is not getting updated and the form submit reads the state of the main items. Not sure why the element is a t instead of an input.

What have I missed?

One other note (not sure if this affects it): once installed the page could not find the bootstrap-datetimepicker.css file.  I had to explicitly add a path to it and put it in the /public folder ( is used for the grunt build output). Shouldn't have that been picked up automatically?

Any help is appreciated.

**Comment by chollier** [comment]
Hey,

There is no such things as a `value` / `valueLink` / `label` prop. Please have a look at the documentation to see the list of available props : https://github.com/quri/react-bootstrap-datetimepicker#datetimefield
You can also look at the controlled component example in http://dev.quri.com/react-bootstrap-datetimepicker/

But in a nutshell : you need to use the `dateTime` prop.

**Comment by ADumaine** [comment]
There are indeed valuelink and label props in the classes with the template I started with (aqua). The valueLink is part of the Two-Way Binding Helpers (https://facebook.github.io/react/docs/two-way-binding-helpers.html).  It turns out the template has separate components in separate jsx files for re-usability. There is a Form component which has a ControlGroup component, which can have sub components such as SelectCrontrol, TextAreaControl, etc.  I tried creating the DateTimeControl.jsx but there are too many levels of communication between the children and parents for me to get this working.

For now I ended up putting the DateTimeField in the main form and tied it to the forms state. I will have to do this in every form which breaks the idea of reusable components.  I only started using react last week and I have to learn more to bubble up the changes in state from date component up three levels to the form state (unless someone has an example).

This is what I have currently in my form component which uses React.addons.LinkedStateMixin that handles the linkedValue:

```javascript
 handleDateChange: function (dateTime) {
        console.log("newDate", dateTime);
        this.setState({ start_time: dateTime});
    },
```
And my DateTimeField looks like (date is from mysql so using ISO format):
```javascript
  <DateTimeField name="start_time"
      ref="start_time"
      dateTime={this.props.data.start_time}
      showToday={false}
      hasError={this.props.data.hasError.start_time}
      valueLink={this.linkState('start_time')}
      inputFormat='MM/DD/YYYY hh:mm A'
      format=''
      onChange={this.handleDateChange}
      help={this.props.data.help.start_time}
      disabled={this.props.data.loading} />
```
The DateTimeField now updates the state of the form and submits the new date correctly but this is not the ideal solution since it has to rely on a function to set the state (none of the other controls do, but I understand the datetimepicker is a lot more complex).  The LinkedStateMixin uses the 'value' field to keep the states updated.  Perhaps if the datetimepicker used 'value' instead of 'datetime' it would work.

**Comment by ADumaine** [comment]
So after walking away from this and clearing my head, I was able to get it to work with the separate control.  Part of the issue was in the DateTimeControl.jsx where I was setting the dateTime to  this.props.start_time.  I finally figure out that the value needed to come from the definition in the main form for dateTime, not start_time.  That brought the initial value over so the field and widget initialized correctly.

I removed the valueLink from both the DateTimeField in the main form and the DateTimeControl.jsx.

Here it the field from the form (the handleDateChange is the same as in the last post).
```javascript
 <DateTimeField name="start_time"
          ref="start_time"
          label="Start Date and Time"
          dateTime={this.props.data.start_time}
          showToday={false}
          hasError={this.props.data.hasError.start_time}
          inputFormat='MM/DD/YYYY hh:mm A'
          format=''
         onChange={this.handleDateChange}
         help={this.props.data.help.start_time}
         disabled={this.props.data.loading} />
```

Here is my current working section from DateTimeControl.jsx  

```javascript
  render: function () {

        var inputClasses = ClassNames(ObjectAssign({
            'form-control': true
        }, this.props.inputClasses));

         return (
            <ControlGroup hasError={this.props.hasError}
                         label={this.props.label}
                          help={this.props.help}>
                <DateTimeField ref="start_time"
                       type={this.props.type}
                       autoCapitalize={this.props.autoCapitalize}
                       className={inputClasses}
                       name={this.props.name}
                       placeholder={this.props.placeholder}
                       dateTime={this.props.dateTime}
                       format=""
                       disabled={this.props.disabled ? 'disabled': undefined}
                       inputFormat='MM/DD/YYYY hh:mm A'
                       showToday ={false}
                       onChange={this.props.onChange}
                        />
            </ControlGroup>
        );
    }
```
The ControlGroup component is in another jsx.  You can find that at https://github.com/jedireza/aqua

After two days of wrestling with this, I think I finally understand the relationships between the components, the props, the state changes and the datepicker.  I hope this helps someone else.
