### ISSUE TITLE
Using React-bootstrap-datetimepicker in Browser globals

### ISSUE THREAD

**Issue by babyboypk** [quri/react-bootstrap-datetimepicker#9]
how to Using React-bootstrap-datetimepicker in Browser globals.

**Comment by chollier** [comment]
Hi @babyboypk 

If you are using bower, here is a way to use the datetimepicker :

```html
<script src="./bower_components/react/react-with-addons.js"></script>
<script src="./bower_components/react-bootstrap/react-bootstrap.js"></script>
<script src="./bower_components/moment/moment.js"></script>
<script src="./bower_components/react-bootstrap-datetimepicker/dist/react-bootstrap-datetimepicker.js"></script>

<body>

<script>
React.render(React.createFactory(ReactBootstrapDatetimepicker)(), document.body);
</script>
```

or if you use JSX :

```jsx
React.render(<ReactBootstrapDatetimepicker />, document.body);
```

In practice, you would also want to include the css, that you can find there https://github.com/quri/react-bootstrap-datetimepicker/blob/master/examples/bootstrap-datetimepicker.min.css

This make me realize I probably should be including it in the dist/ directory.
