### ISSUE TITLE
v0.0.19 does not work due to babel-runtime missing

### ISSUE THREAD

**Issue by torarvid** [quri/react-bootstrap-datetimepicker#90]
Whenever I require this component from my own project, I get `Error: Cannot find module 'babel-runtime/helpers/get' from '/Users/torarvid/src/wowbox/node_modules/react-bootstrap-datetimepicker/lib'`

I see babel-runtime being included in the `devDependencies` inside `package.json`, but it looks to me like this is needed by the dist as well (though I'm not sure I understand this correctly)

package.json lists `./lib/DateTimeField.js` as its `main`, and this file has many references to 
`babel-runtime`

**Comment by chollier** [comment]
Hi @torarvid,

Thanks for reporting this, my bad ! I just moved babel-runtime from devDependencies to dependencies in package.json, that should fix it. I pushed `0.0.20` would you mind trying with it ? thanks.

**Comment by torarvid** [comment]
Works now, thanks!

(I now seem to have a different issue - when I click to open the picker, it anchors on the top right of the page, instead of the button I clicked - but that might be my own fault... I'll investigate and open another issue if I figure it out)

**Comment by chollier** [comment]
@torarvid you might have forgotten to include the css that is available on the package :)
