### ISSUE TITLE
Where is Version 0.0.20? Need latest code to submit pull request against.

### ISSUE THREAD

**Issue by kenleezle** [quri/react-bootstrap-datetimepicker#94]
on npm the latest is 0.0.20.
It appears that npm has a later version than github.

For example:
DateTimeField.js on master has 366 lines.
DateTimeField.js in npm version 0.0.20 has 426 lines.

I would like to submit a pull request, however I would like to do it based on the latest code.

**Comment by chollier** [comment]
You can see here https://github.com/quri/react-bootstrap-datetimepicker/commits/master that master includes 0.0.20 version bump. Indeed I forgot to push the tag which I just did.

**Comment by chollier** [comment]
The version on npm is not that same as the one on github because before publishing on npm the code goes through babel (see `npm run build-npm` on package.json) that makes it compatible for people who don't use ES6.
